language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  
  
before_script:
  - composer self-update
  
  
script: php -l index.php && php -l register_login.php && php -l register_register.php && php -l register_token.php
