CREATE TABLE login_failed (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ip VARCHAR(50) NOT NULL,
time INT NOT NULL
);

CREATE TABLE login_success (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
uid INT NOT NULL,
ip VARCHAR(50),
time INT NOT NULL
);

CREATE TABLE sessions (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
uid INT NOT NULL,
sid VARCHAR(100) NOT NULL,
start_time INT NOT NULL,
last_active INT NOT NULL,
ip VARCHAR(50) NOT NULL,
active TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE `user` (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(20) NOT NULL,
password VARCHAR(80) NOT NULL,
salt VARCHAR(20) NOT NULL,
register_time INT NOT NULL,
email VARCHAR(100) NOT NULL,
activated TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE user_tokens (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
token VARCHAR(100) NOT NULL,
uid INT NOT NULL,
action SET('active', 'changepw', 'changeemail', '') NOT NULL,
time INT NOT NULL,
email VARCHAR(100)
);
